# Generated by Django 4.1.1 on 2022-11-05 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0018_alter_issues_total_data_entry_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProjectBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('salary', models.FloatField(blank=True, default=0, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project')),
                ('receivers', models.ManyToManyField(related_name='worker_payments', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
