# Generated by Django 4.1.1 on 2022-11-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentprojectbased',
            options={'verbose_name_plural': 'Payments Employe'},
        ),
    ]
