# Generated by Django 4.1.1 on 2022-11-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentprojectbased_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprojectbased',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentprojectbased',
            name='per_entry',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
