# Generated by Django 4.1.1 on 2022-11-08 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentprojectbased_is_accept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprojectbased',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
