# Generated by Django 4.1.1 on 2022-11-11 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentprojectbased_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentprojectbased',
            options={'verbose_name_plural': 'Payments Employee'},
        ),
    ]
