# Generated by Django 4.1.1 on 2022-11-12 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0006_alter_paymentprojectbased_receivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprojectbased',
            name='receivers',
            field=models.ManyToManyField(related_name='worker_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
