# Generated by Django 4.1.1 on 2022-11-12 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0010_remove_paymentprojectbased_receivers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentprojectbased',
            name='receivers',
        ),
        migrations.AddField(
            model_name='paymentprojectbased',
            name='receivers',
            field=models.ManyToManyField(related_name='worker_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
