# Generated by Django 4.1.1 on 2022-11-12 22:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_issues_status_alter_project_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0011_remove_paymentprojectbased_receivers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentProjectBased',
            new_name='Payments',
        ),
    ]
