# Generated by Django 4.1.1 on 2022-10-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksubmission',
            old_name='task',
            new_name='project',
        ),
    ]
