# Generated by Django 4.1.1 on 2022-10-23 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_categories_project_categor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='categor',
            new_name='category',
        ),
    ]
