# Generated by Django 4.1.1 on 2022-10-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_categor_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('stuck', 'Stuck'), ('working', 'Working'), ('done', 'Done')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.CharField(choices=[('on due', 'On Due'), ('overdue', 'Overdue'), ('done', 'Done')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('stuck', 'Stuck'), ('working', 'Working'), ('done', 'Done')], default=1, max_length=7),
        ),
    ]
