# Generated by Django 4.1.1 on 2022-10-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_status_alter_task_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sort_description',
            field=models.CharField(default='sort description', max_length=300),
            preserve_default=False,
        ),
    ]
