# Generated by Django 4.1.1 on 2022-10-28 23:04

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_complete_per_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_start_work', models.DateTimeField()),
                ('today_end_work', models.DateTimeField()),
                ('total_data_entry_today', models.CharField(max_length=254)),
                ('file', models.FileField(max_length=254, upload_to='project_submission')),
                ('description', django_quill.fields.QuillField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to='projects.project')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskSubmission',
        ),
    ]
