# Generated by Django 4.1.1 on 2022-10-28 23:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectsubmission_delete_tasksubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubmission',
            name='today_end_work',
        ),
        migrations.RemoveField(
            model_name='projectsubmission',
            name='today_start_work',
        ),
        migrations.RemoveField(
            model_name='projectsubmission',
            name='total_data_entry_today',
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='status',
            field=models.CharField(choices=[('stuck', 'Stuck'), ('working', 'Working'), ('done', 'Done')], default=1, max_length=7),
        ),
        migrations.CreateModel(
            name='TaskIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('stuck', 'Stuck'), ('working', 'Working'), ('done', 'Done')], default=1, max_length=7)),
                ('due', models.CharField(choices=[('on due', 'On Due'), ('overdue', 'Overdue'), ('done', 'Done')], default=1, max_length=7)),
                ('today_start_work', models.DateTimeField()),
                ('today_end_work', models.DateTimeField()),
                ('total_data_entry_today', models.CharField(max_length=254)),
                ('is_active', models.BooleanField(default=False)),
                ('complete_per', models.FloatField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('file', models.FileField(upload_to='task_issues')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.task')),
            ],
            options={
                'verbose_name_plural': 'Task Issues',
            },
        ),
    ]
