# Generated by Django 4.1.1 on 2022-10-28 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_projectsubmission_today_end_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_per',
            field=models.FloatField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
