# Generated by Django 4.1.1 on 2022-10-30 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_task_complete_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskissues',
            name='project',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project'),
            preserve_default=False,
        ),
    ]
