# Generated by Django 4.1.1 on 2022-10-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_taskissues_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskIssues',
            new_name='Issues',
        ),
        migrations.AlterModelOptions(
            name='issues',
            options={'verbose_name_plural': 'Issues'},
        ),
    ]
