# Generated by Django 4.1.1 on 2022-10-31 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_rename_taskissues_issues_alter_issues_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.task'),
        ),
    ]
