# Generated by Django 4.1.1 on 2022-10-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_issues_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='today_end_work',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='issues',
            name='today_start_work',
            field=models.TimeField(),
        ),
    ]
