# Generated by Django 4.1.1 on 2022-11-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_issues_today_end_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='total_data_entry_today',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
