# Generated by Django 4.1.1 on 2022-11-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_issues_total_data_entry_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='total_data_entry_today',
            field=models.CharField(blank=True, default=0, max_length=254, null=True),
        ),
    ]
