# Generated by Django 4.1.1 on 2022-11-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_accept_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='accept_status',
            field=models.CharField(choices=[('draft', 'draft'), ('decline', 'decline'), ('accept', 'accept'), ('pending', 'pending')], default=('draft', 'draft'), max_length=15),
        ),
    ]
