# Generated by Django 4.1.1 on 2022-11-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_project_accept_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('stuck', 'Stuck'), ('working', 'Working'), ('done', 'Done')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('stuck', 'Stuck'), ('working', 'Working'), ('done', 'Done')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('stuck', 'Stuck'), ('working', 'Working'), ('done', 'Done')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('stuck', 'Stuck'), ('working', 'Working'), ('done', 'Done')], default=1, max_length=7),
        ),
    ]
