# Generated by Django 4.1.1 on 2022-10-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('leader', 'leader'), ('worker', 'worker')], default='worker', max_length=100),
        ),
    ]
