# Generated by Django 4.1.1 on 2022-10-23 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_acc_num', models.CharField(max_length=255)),
                ('acc_holder_name', models.CharField(max_length=255)),
                ('acc_branch_name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bankinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
