# Generated by Django 4.1.1 on 2022-10-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bankinformation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankInformation',
            new_name='Bank',
        ),
    ]
