# Generated by Django 4.1.1 on 2022-10-23 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_bankinformation_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='user',
        ),
        migrations.AddField(
            model_name='bank',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='accounts.profile'),
            preserve_default=False,
        ),
    ]
