# Generated by Django 4.1.1 on 2022-10-23 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_bank_user_bank_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name_plural': 'Users Bank Info'},
        ),
    ]
