# Generated by Django 4.1.1 on 2022-11-03 21:02

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=django_quill.fields.QuillField(),
        ),
    ]
