# Generated by Django 4.1.1 on 2022-11-03 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_notification_from_admin_notification_from_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='from_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='from_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
